### ISSUE TITLE
set_all() method stopped working 

### ISSUE THREAD

**Issue by iSayeed** [romainsacchi/carculator#24]
Everytime when I run the set_all method this is what I get. Something related to pickle I can see
![carculator](https://user-images.githubusercontent.com/49028383/123775465-afd88f80-d8ce-11eb-9a89-ff3011bc1e32.JPG)

**Comment by romainsacchi** [comment]
Hello @iSayeed,

I think this is due to a recent update of `xarray` to 0.18. I will add in the requirements to downgrade to xarray 0.17.
Try to do the same on your end, this should solve your issue.

**Comment by iSayeed** [comment]
Thanks! it is working now :)
