### ISSUE TITLE
ValueError: unsupported pickle protocol: 5

### ISSUE THREAD

**Issue by Shima-Fa** [romainsacchi/carculator#29]
@romainsacchi 
Good day Mr. Sacchi,
after installing the new version of carculator (1.8), unfortunately I get the value error "unsupported pickle protocol: 5" directly right after `import carculator` command. 

The package from `conda install -c romainsacchi carculator` looks like has some version control problem, then I decided to install the package from PyPi but looks like the problem is still there. 

I would appreciate any help regarding this issue

**Comment by romainsacchi** [comment]
Also, try to install `carculator 1.8.1` instead of `1.8.0`.

**Comment by Shima-Fa** [comment]
Thank you very much, that solved the problem!
