### ISSUE TITLE
Glider base masses

### ISSUE THREAD

**Issue by A-Sterni** [romainsacchi/carculator#34]
I was wondering if it wouldn't make sense to consider equal glider base masses for all powertrains because all powertrain specific masses are considered separately.

In particular, I was wondering about the following weights:
- Large vehicle: PHEV-e weights 1650 kg all others 1550 kg
- Mini vehicle: PHEV-e weights 810 kg all others 700 kg
- Medium SUV: BEV and PHEV-e weight 1400 kg all others 1200 kg. 
<img width="380" alt="Weights" src="https://github.com/romainsacchi/carculator/assets/151236706/1db42cd1-f6b9-443b-b487-2c2fef81bff2">

**Comment by romainsacchi** [comment]
Hi @A-Sterni,

indeed. This comes from calibrating the default masse values when checking against [the EU database](https://co2cars.apps.eea.europa.eu/?source=%7B%22track_total_hits%22%3Atrue%2C%22query%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22constant_score%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22bool%22%3A%7B%22should%22%3A%5B%7B%22term%22%3A%7B%22year%22%3A2022%7D%7D%5D%7D%7D%2C%7B%22bool%22%3A%7B%22should%22%3A%5B%7B%22term%22%3A%7B%22scStatus%22%3A%22Provisional%22%7D%7D%5D%7D%7D%5D%7D%7D%7D%7D%5D%7D%7D%2C%22display_type%22%3A%22tabular%22%7D).
We played on the glider mass to ensure we matched the average vehicle mass of a specific size and powertrain type. It would have been smarter of me to adjust the lightweight rate instead.

When I'll find some time, I'll correct this, but this requires some work.

**Comment by romainsacchi** [comment]
Effect on GWP form harmonizing `glider base mass` across powertrains (positive pct = decrease relative to old values).

| powertrain | Large | Large SUV | Lower medium | Medium | Medium SUV | Mini | Small | Van |
| ---------- | ----- | --------- | ------------ | ------ | ---------- | ---- | ----- | --- |
| BEV        | 0%    | 0%        | 0%           | 0%     | 6%         | 0%   | 0%    | 4%  |
| FCEV       | 0%    | 0%        | 0%           | 0%     | 0%         | 0%   | \-3%  | 4%  |
| HEV-d      | 0%    | 0%        | 3%           | 2%     | 0%         | 0%   | 1%    | 8%  |
| HEV-p      | 0%    | 0%        | 3%           | 2%     | 0%         | 0%   | 0%    | 8%  |
| ICEV-d     | 0%    | 0%        | 0%           | 0%     | 0%         | 0%   | 1%    | 4%  |
| ICEV-g     | 0%    | 0%        | 0%           | 0%     | 0%         | 0%   | \-3%  | 4%  |
| ICEV-p     | 0%    | 0%        | 0%           | 0%     | 0%         | 0%   | 0%    | 5%  |
| PHEV-d     | 2%    | 0%        | 0%           | 1%     | 4%         | 2%   | 2%    | 7%  |
| PHEV-p     | 2%    | 0%        | 0%           | 3%     | 4%         | 2%   | 1%    | 6%  |

**Comment by romainsacchi** [comment]
Typical extreme change would be `Medium SUV BEV` (before: 0.169gCO2e, after: 0.158).

**Comment by romainsacchi** [comment]
New values for `glider base mass`:

| powertrain | Large | Large SUV | Lower medium | Medium | Medium SUV | Micro | Mini | Small | Van  |
| ---------- | ----- | --------- | ------------ | ------ | ---------- | ----- | ---- | ----- | ---- |
| BEV        | 1550  | 1900      | 1170         | 1350   | 1200       | 350   | 700  | 1000  | 1450 |
| FCEV       | 1550  | 1900      | 1170         | 1350   | 1200       | 0     | 700  | 1000  | 1450 |
| HEV-d      | 1550  | 1900      | 1170         | 1350   | 1200       | 0     | 700  | 1000  | 1450 |
| HEV-p      | 1550  | 1900      | 1170         | 1350   | 1200       | 0     | 700  | 1000  | 1450 |
| ICEV-d     | 1550  | 1900      | 1170         | 1350   | 1200       | 0     | 700  | 1000  | 1450 |
| ICEV-g     | 1550  | 1900      | 1170         | 1350   | 1200       | 0     | 700  | 1000  | 1450 |
| ICEV-p     | 1550  | 1900      | 1170         | 1350   | 1200       | 0     | 700  | 1000  | 1450 |
| PHEV-d     | 1550  | 1900      | 1170         | 1350   | 1200       | 0     | 700  | 1000  | 1450 |
| PHEV-p     | 1550  | 1900      | 1170         | 1350   | 1200       | 0     | 700  | 1000  | 1450 |

**Comment by romainsacchi** [comment]
Re-open if you think the issue is not resolved.
