### ISSUE TITLE
Combustion noise calculations possibly incorrect

### ISSUE THREAD

**Issue by cmutel** [romainsacchi/carculator#8]
If I read [this correctly](https://github.com/romainsacchi/carculator/blob/master/carculator/noise_emissions.py#L125), the combustion noise only kicks in above 20 km/h - but the rolling noise also only kicks in above 20 km/h. Is there no noise for slower combustion cars?

**Comment by romainsacchi** [comment]
It seems to be a limitation of the CNOSSOS model. See p.33 equation III-2 of http://publications.jrc.ec.europa.eu/repository/bitstream/JRC72550/cnossos-eu%20jrc%20reference%20report_final_on%20line%20version_10%20august%202012.pdf

The model is only valid for vm (20 km/h ≤ vm ≤ 130 km/h).

**Comment by cmutel** [comment]
It seems weird to penalize electric cars when we know that combustion cars also make noise at that speed - maybe more consistent then to set everyone to zero < 20 km/h? Or set everyone to 56 dB, as electric cars should mimic combustion cars...

**Comment by romainsacchi** [comment]
I agree. But I'm not sure how to proceed about this. IMO, your second suggestion suggestion seems more correct than the first one. Although I am not sure that the value of 56 dB is meant to equal the noise made by combustion cars below 20 km/h. It's maybe just loud enough to be heard.

**Comment by romainsacchi** [comment]
Fig. on slide 8 of this paper (https://www.unece.org/fileadmin/DAM/trans/doc/2009/wp29grb/ECE-TRANS-WP29-GRB-49-inf10e.pdf) shows that, below 20 km/h, the difference between hybrid and combustion cars is significant if no artificial warning sound is added (approx. 20 dBA, when both stopped). Below 20 km/h, hybrid cars can be considered similar to electric cars (as they both run electric at that speed). When idle, combustion cars have a total noise of 45-50 dB it seems (which may correspond to around 56 dBA). So, adding 56 dB to electric cars will indeed penalize them, considering combustion cars probably make more or less the same amount of noise. Can it be an option to add noise to combustion cars based on the figure of this presentation?

**Comment by cmutel** [comment]
I leave it to you to pick the best approach. As we have seen, the differences are not so great, so don't worry too much about it.
